### ISSUE TITLE
Support for variant type in snowflake table

### ISSUE THREAD

**Issue by Pangstar** [snowflakedb/spark-snowflake#16]
The current implementation does not support variant types and errors when one of my data types in my dataframe is an array. would it be possible to support arraytypes to json?

Is this an open source project am I ok to fork/ contribute?

**Comment by etduwx** [comment]
Hi @Pangstar ,

Yes! Feel free to fork this project and create a Pull Request for any feature/bug-fix you would like to contribute.

It is valuable to have support for nested data types in the connector (not just arrays but variants), since Spark DataFrames support these types. JSON is a natural choice as a data export format.

Things you'll need to change, off the top of my head:

- Schema resolution in `SnowflakeJDBCWrapper`. Currently, we use JDBC's metadata getter to determine the types. However, since `ARRAY` and `VARIANT` type columns show up as `VARCHAR`, you might consider running a `DESC table` query to figure that out.
- The generated `COPY` statement in `DataUnloader`. The tricky part here is that Snowflake `COPY` with JSON only works when the input is a single `VARIANT`, `ARRAY`, or `OBJECT` type column, and if we've got a mixture of column types in a table, you'll need to squish things down into a single, properly formatted, JSON column. This is possible with a combination of functions like `parse_json`, `array_to_string`, and `concat` to transform the values in each row into this format. Another way might be to unload these columns separately from the well-structured columns, and then join these files together, though this obviously has its own disadvantages.
- `SnowflakeRDD` and `SnowflakeInputFormat` if you also want to add this functionality for when using Snowflake's internal staging area, as we'll need to parse JSON files different from CSV ones. Otherwise, we can use Spark's CSV reader.

The changes would likely be significant, but would be really useful. Thanks for this! Let me know if you would  like some more help.

**Comment by Pangstar** [comment]
Thanks - I'll give this a bash. Will definitely have more questions.
